adds floors to database
hpi-swt2/compass-portal-red pull request #144
Opened 2022-01-09 14:04 UTC by LeonHermann322

Closes: #134

Added Floors to database. Floors have rooms and Buildings have Floors.

Co-authored-by: Nikola Genchev <kolioOtSofia@users.noreply.github.com>
Co-authored-by: Benjamin Frost <Benjamin-Frost@users.noreply.github.com>

2022-01-12 14:57 UTC, SebastianWagner2 requested changes
Most of the changes are about whether rooms should have a nullable floor and whether floors should have a nullable building
We should talk about it on DC

2022-01-12 14:57 UTC, SebastianWagner2 commented on app/helpers/indoor_helper.rb
> +    floor = Floor.create(name: 'Example Floor', building: building)
Remove this for now, floors aren't being parsed yet. Mocking it may lead to confusion

2022-01-12 14:57 UTC, SebastianWagner2 commented on app/models/floor.rb
> +  belongs_to :building, optional: true # optional, because floors should be creatable without creating a building
```suggestion
  belongs_to :building
```
I would remove optional, there cannot be a floor outside of a building (just assure the building is created before the floor)

2022-01-12 14:57 UTC, SebastianWagner2 commented on app/models/floor.rb
> +    # TODO
Does this need to be done before merging?

2022-01-12 14:57 UTC, SebastianWagner2 commented on app/models/room.rb
> +  belongs_to :floor, optional: true # optional, because rooms should be creatable without creating a floor
```suggestion
  belongs_to :floor
```
I would remove optional, there cannot be a floor outside of a building (just assure the building is created before the floor)

2022-01-12 14:57 UTC, SebastianWagner2 commented on spec/factories/rooms.rb
> -    floor { "E" }
I would add this line again (see above, i opted against making the floor nullable)

2022-01-12 14:57 UTC, SebastianWagner2 commented on db/migrate/20220109135029_add_rooms_to_floor.rb
> +    add_reference :rooms, :floor, null: true, foreign_key: true
```suggestion
    add_reference :rooms, :floor, null: true, foreign_key: true
```
Would alter it to null: false (via new migration tho)

2022-01-12 14:57 UTC, SebastianWagner2 commented on spec/models/floor_spec.rb
> +require 'rails_helper'
I guess it needs to be added before merging

2022-01-15 16:04 UTC, SebastianWagner2 reviewed
Shouldn't review my code

2022-01-15 19:14 UTC, kolioOtSofia approved these changes

2022-01-16 09:21 UTC, Benjamin-Frost approved these changes

2022-01-16 09:22 UTC, merged