104 export hs building as seed
hpi-swt2/compass-portal-red pull request #168
Opened 2022-01-17 11:47 UTC by elenagensch

- [x] Adds rake task  export:export_to_seeds for
-  - [x]  retrieving Point, PointOfInterest, Polyline, Wall, Room and Building from db
-  - [x]  logging corresponding create statements

 - [x] seed building data (add logged statements to seeds.rb)
 
![image](https://user-images.githubusercontent.com/68114173/149659181-51d40fb3-939e-4911-b624-2944fe45b0f8.png)

2022-01-17 15:51 UTC, SebastianWagner2 requested changes
Thanks for updating the seeding to our changes :)

Co-authored-by: benjamin-frost <bfrost.schule@gmail.com>
Co-authored-by: LeonHermann322 <leon.hermann@student.hpi.uni-potsdam.de>
Co-authored-by: Toalaah <samuel.kunst@gmail.com>
Co-authored-by: kolioOtSofia <n.genchev@hotmail.com>
Co-authored-by: Tinus Lorvalds <torvalds@linux-foundation.org>

2022-01-17 15:51 UTC, SebastianWagner2 commented on db/seeds.rb
>    [ "H-2.3", floor, "Bachelorprojekt Baudisch"],
Please remove the room list, the rooms in it end up being nonsensical (no outer line)

2022-01-17 15:51 UTC, SebastianWagner2 commented on db/seeds.rb
> +  [floor, "R3", 7],
```suggestion
  [floor, "Passage", 2],
  [floor, "HS 2", 3],
  [floor2, "Foyer", 4],
  [floor2, "R1", 5],
  [floor, "R2", 6],
  [floor, "R3", 7],
```
Please use both first and second floor (we need to test smth)

2022-01-17 15:51 UTC, SebastianWagner2 commented on db/seeds.rb
>  end
```suggestion
point_list.each do |point|
  Point.create(point)
end

point_of_interest_list.each do |point_of_interest|
  PointOfInterest.create(point_of_interest)
end

polyline_list.each do |polyline_points|
  Polyline.create(points: polyline_points.map { |point_id| Point.find(point_id) })
end

bundle = person_collection.zip hs_rooms

bundle.each do |person, room|
  outer_shape = Polyline.find(room[2]) if room[2].present?
  Room.create(number: room[0], floor: room[1], full_name: room[2], people: [person])
end

room_type_list.each do |room_type|
  RoomType.create(name: room_type[0])
end
```

2022-01-17 15:51 UTC, SebastianWagner2 commented on db/seeds.rb
>  end
Fixed this not to use rooms_list anymore (use hs_rooms instead)

Am not sure about lines 166 through 169, looks to me like the same room may be created several times (not sure though)

2022-01-18 11:57 UTC, cedric-lorenz approved these changes

2022-01-18 11:57 UTC, cedric-lorenz commented on db/seeds.rb
> +  ['D-K.1', floor2, "ping pong", 4],
```suggestion
  ['D-K.1', floor2, "Ping Pong", 4],
```

2022-01-18 12:03 UTC, cedric-lorenz approved these changes

2022-01-18 12:11 UTC, merged

2022-01-18 13:14 UTC, elenagensch commented on db/seeds.rb
> +  ['D-K.1', floor2, "ping pong", 4],
👍