fix: all points get replaced, even outside of coordinates
hpi-swt2/compass-portal-red pull request #202
Opened 2022-01-21 13:32 UTC by PaulVII

The previous implementation would convert compass-red.herokuapp.com to compass-redpherokuapppcom

2022-01-21 13:53 UTC, 23mafi commented on app/javascript/packs/router.js
> +        url = url.replaceAll(',', '%2C')
nach dem ersten Komma würde ich dann auch ein Leerzeichen machen

2022-01-21 13:57 UTC, 23mafi requested changes
Wir können jetzt zwar wieder die Routen planen, allerdings verursacht die Ersetzung der Punkte mit p bei der Anzeige zu ein paar Problemen:
Im Routing Container stehen keine Koordinaten mehr, weil wir ja die Punkt mit p ersetzt haben und wenn man zoom verschieben sich die Marker der Start und Endposition.
Als einfachste Lösung würde mir jetzt spontan einfallen, dass man vor der Anzeige bei den  Kooridinaten die ps wieder mit Punkten ersetzt.
https://user-images.githubusercontent.com/68427675/150539224-a3e70c23-422b-4bc3-84ed-90efb95a4e68.mov

2022-01-21 14:03 UTC, PaulVII commented on app/javascript/packs/router.js
> +        url = url.replaceAll(',', '%2C')
> nach dem ersten Komma würde ich dann auch ein Leerzeichen machen

Sorry, ich verstehe nicht ganz was du meinst. Geht es um das Leerzeichen zwischen , und '%2C' ? Das hat der Linter überall bei mir gesetzt

2022-01-21 16:11 UTC, PaulVII commented
> Wir können jetzt zwar wieder die Routen planen, allerdings verursacht die Ersetzung der Punkte mit p bei der Anzeige zu ein paar Problemen: Im Routing Container stehen keine Koordinaten mehr, weil wir ja die Punkt mit p ersetzt haben und wenn man zoom verschieben sich die Marker der Start und Endposition. Als einfachste Lösung würde mir jetzt spontan einfallen, dass man vor der Anzeige bei den Kooridinaten die ps wieder mit Punkten ersetzt. https://user-images.githubusercontent.com/68427675/150539224-a3e70c23-422b-4bc3-84ed-90efb95a4e68.mov

Ah, ich erstelle jetzt neue Objekte statt sie zu verändern, damit sollte das Problem gelöst sein. Hat beim Testen auf 127.0.0.1 (also nicht localhost) geklappt

2022-01-25 09:24 UTC, jannikgro approved these changes

2022-01-25 09:43 UTC, 23mafi approved these changes
Looks good for me :)

2022-01-25 11:06 UTC, merged