177 update search bar design
hpi-swt2/compass-portal-red pull request #216
Opened 2022-01-25 22:42 UTC by lucasliebe

This Pull Request will change the visuals of the search page to a more cleaner look. A Search can now be started by pressing enter and cleared using the cross, that is only visible when text is entered.
![image](https://user-images.githubusercontent.com/33379641/151071981-068113b0-ba00-41f0-860e-66ce48de6034.png)

2022-01-26 11:54 UTC, kpostnov requested changes
There is a couple of issues I have with that PR so far:

- The page looks very empty now, both on desktop and mobile. Someone using the website for the first time might not know what the site is for and what to do. Maybe a short introductory text could be useful.
- I believe there is a nicer "x" that isn't just the actual character and might look more appealing. The "x" could use a white background as well for better readability when writing long queries.
- I feel like there should be another way than reloading the page to clear the input.

Bootstrap should have a predefined design for input forms with icons. Something like this: https://stackoverflow.com/questions/45696685/search-input-with-an-icon-bootstrap

2022-01-26 12:18 UTC, treyfel commented on app/assets/stylesheets/search.scss
> +.cancel-input{
maybe add a border radius here

2022-01-26 13:12 UTC, FranzSw commented
I agree with Kirill.

> The page looks very empty now, both on desktop and mobile. Someone using the website for the first time might not know what the site is for and what to do. Maybe a short introductory text could be useful.

I would keep the search bar at top, maybe short intro text below?
Also a placeholder in the field might already be enough ("Suche nach Räumen, Personen, ...")

> I feel like there should be another way than reloading the page to clear the input.

Imho, the results dont have to be cleared when clicking the X, that might make it a bit easier?

2022-01-26 13:23 UTC, kpostnov commented
> I would keep the search bar at top, maybe the short intro text below? Also a placeholder in the field might already be enough ("Suche nach Räumen, Personen, ...")

Apparently there is another issue for that (#213). But the placeholder sounds good.

> Imho, the results dont have to be cleared when clicking the X, that might make it a bit easier?

I agree. Usually it's done this way.

2022-01-27 14:32 UTC, lucasliebe commented
I now changed some of your recommendations the rest was cleared in discussion with the PO

2022-01-27 15:03 UTC, kpostnov submitted a review, later dismissed
# Looks not fine to me now

2022-01-27 15:24 UTC, kpostnov approved these changes

2022-01-27 15:24 UTC, merged