182 Highlight the building I want to go differently
hpi-swt2/compass-portal-red pull request #234
Opened 2022-01-28 16:45 UTC by SinNeax

We added the following functionalities:

- highlight the destination building with colour "red"
- reset the highlighted building colour to its original one on Stop-Button-Click or when clicking outside of the highlighted building
- the highlighted colour remains when zooming in or out (at indoor mode, the contour of the building remains in the highlighted colour)

closes #182

2022-01-28 20:04 UTC, t-straeubig requested changes

2022-01-28 20:04 UTC, t-straeubig commented on app/javascript/packs/outdoor_map_builder.js
> +function highlightDestinationDifferently(position) {
der Methodenname ist eetwas suboptimal zum Verständnis, besonders in Verbindung mit der anderen Methode `setStyleForHighlightedBuilding` wird die Aufgabenteilung nicht sonderlich klar. Die Methode hier findet hauptsächtlich heraus, welches Gebäude in der gegebenen Position liegt, setzt dann die highlightedBuilding Variable auf diese und setzt dann den Style (was ein logischer Schritt ist, nachdem man das geändert hat, aber es ist halt nicht was die Methode hauptsächlich tut). Ich fänd z.B. `changeHighlightedBuilding` besser.

2022-01-28 20:44 UTC, NikkelM commented on app/javascript/packs/outdoor_map_builder.js
> +  if ((zoom < standardZoomLevel || zoom > indoorZoomLevel)) {
Wenn ihr genauer draufschaut werdet ihr bemerken, dass die immer zu true evaluiert. Wir haben sie auch einmal für alle zoom-Level laufen (loggen) lassen, und auch immer true bekommen, daher haben wir sie entfernt.

2022-01-28 20:45 UTC, NikkelM commented on app/javascript/packs/outdoor_map_builder.js
> +          setStyleForHighlightedBuilding(true);
Hmm, müsste ich jetzt auch genauer noch einmal in den Code schauen. Wir haben unser style-setzen einfach überall dort eingeführt, wo hier anderweitig styles gesetzt wurden

2022-01-28 20:52 UTC, NikkelM commented on app/javascript/packs/outdoor_map_builder.js
> +        highlightedBuilding = buildingsOfCampus[buildingId];
Guter Punkt, wir hatten die setStyle-Methode erst nach der Implementation dieser Methode gemacht und das daher übersehen. Den Bug habe ich auch gerade reproduziert, da müssen wir mal schauen, wie wir die Fallunterscheidung gut machen, wie ihr sicher auch schon gesehen habt, ist der zoom-Code nicht sehr schön zu lesen

2022-01-31 13:43 UTC, NikkelM commented on app/javascript/packs/outdoor_map_builder.js
> +          setStyleForHighlightedBuilding(true);
Ich habe deinen Kommentar weiter unten umgesetzt, dadurch wird die Methode jetzt auch nur einmal in der "zoomend" aufgerufen

2022-01-31 17:24 UTC, t-straeubig commented on app/javascript/packs/outdoor_map_builder.js
> +  if ((zoom < standardZoomLevel || zoom > indoorZoomLevel)) {
ich denke wer auch immer diese Zeile ursprünglich geschrieben hat, hat sich vertan.  Die Intention der Bedingung ist glaube ich abzufragen, ob man jetzt außerhalb des Intervalls ist, aber es zuvor war. In diesem Fall müssten es aber
`!lastZoom || (lastZoom >= standardZoomLevel && lastZoom <= indoorZoomLevel)` lauten
Man müsste jetzt denjenigen mal aufsuchen der das gemacht hat und fragen ob das wirklich seine Intention war. Ich schätze aber es ist riskant das einfach rauszunehmen, auch wenn es tatsächlich im Code keine Funktion mehr erfüllt hat. Vielleicht lasst ihr es lieber drin und sagt dem Autor oder Leo bescheid, dass da zweifelhafter Code ist

2022-01-31 17:33 UTC, t-straeubig requested changes
Sieht viel schöner aus ^^. Eine Kleinigkeit gibts aber noch: Diese Zeile in der If-Abfrage die ihr rausgenommen habt: Ich würd die nicht rausnehmen. Mehr dazu im entsprechenden Kommentar. Achtung, pullt mal nochmal bevor ihr weiterarbeitet. Ich hab eine kleinen Fix in der Einrückung einer Zeile committet

2022-01-31 18:08 UTC, NikkelM commented on app/javascript/packs/outdoor_map_builder.js
> +  if ((zoom < standardZoomLevel || zoom > indoorZoomLevel)) {
Okay, hab ich gemacht.

2022-01-31 18:13 UTC, janina-adamcic approved these changes

2022-01-31 18:13 UTC, t-straeubig approved these changes

2022-01-31 19:20 UTC, merged