Fixes #187
hpi-swt2/compass-portal-red pull request #250
Opened 2022-02-01 22:13 UTC by treyfel

doesnt show students for not logged in users as search results.
Also adds two tests for this. Furthermore unwanted attributes can be added to the code.

2022-02-01 22:14 UTC, treyfel commented on app/views/search/index.html.erb
> +                               ["Telegram"]
This is where you can add attributes, that you don't want not signed in users to see.

2022-02-04 15:11 UTC, lucasliebe reviewed
I think we don't need the role attribute since as I know status is used for separating students and other members of the university. @FranzSw ?

2022-02-04 15:23 UTC, lucasliebe approved these changes

2022-02-04 15:23 UTC, lucasliebe requested changes
if tests run this can be approved

2022-02-08 13:27 UTC, FranzSw approved these changes
Exceptional code quality!

2022-02-09 13:16 UTC, merged